<?php
return array(
    'default' => array(
        'header' => '',
        'footer' => '',
        'maxButtonCount' => 5,
        'firstPageLabel' => '首页',
        'nextPageLabel' => '下页',
        'prevPageLabel' => '上页',
        'cssFile' => false,
    ),
    'bootstrap' => array(
        'header' => '',
        'footer' => '',
        'maxButtonCount' => 5,
        'firstPageLabel' => '首页',
        'firstPageLabel' => '',
        'nextPageLabel' => '下页',
        'prevPageLabel' => '上页',
        'cssFile' => false,
        'hiddenPageCssClass' => 'disabled',
        'selectedPageCssClass' => 'active',
    ),
    'mobile' => array(
        'header' => '',
        'footer' => '',
        'maxButtonCount' => 0,
        'nextPageLabel' => '上一页',
        'prevPageLabel' => '下一页',
        'firstPageLabel' => '',
        'lastPageLabel' => '',
        'cssFile' => false,
        'hiddenPageCssClass' => 'disabled',
        'selectedPageCssClass' => 'active',
    ),
);