<?php
define('DEFAULT_POST_LATEST_COUNT', 30);
define('DEFAULT_POST_HISTORY_COUNT', 30);
define('DEFAULT_POST_RANDOM_COUNT', 30);
define('DEFAULT_POST_FEEDBACK_COUNT', 30);

define('DEFAULT_COMMENT_LATEST_COUNT', 20);
define('DEFAULT_COMMENT_HISTORY_COUNT', 20);